version: 2

models:
  - name: dbt_sfdc_test
    description: "A starter dbt model"
    quoting:
      database: true
      schema: true
    database: "VICTOR_HUSKEY"
    schema: "DBT"
    
sources:
  - name: raw_matillion_salesforce
    schema: raw_matillion_salesforce  # Ensure this matches the schema in Snowflake
    tables:
      - name: program_c
